services:
  - type: web
    name: reformpost
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"